-- =====================================================================
--  JJ KPI · ระบบวัดความพึงพอใจลูกค้า (จริงใจหมูกระทะ)
--  Supabase project: aikyxvluaiubdidqxwnd · table prefix: kpi_
--  รันซ้ำได้ (idempotent) — รันทั้งไฟล์ใน SQL Editor
-- =====================================================================

-- ---------- ตาราง ----------
create table if not exists public.kpi_departments (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  icon        text        not null default '⭐',
  sort_order  int         not null default 0,
  active      boolean     not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.kpi_staff (
  id          bigint generated by default as identity primary key,
  branch      text        not null,            -- JJRD / JJLP
  name        text        not null,
  nickname    text,
  position    text,
  sort_order  int         not null default 0,
  active      boolean     not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.kpi_responses (
  id          bigint generated by default as identity primary key,
  branch      text        not null,
  biz_date    date        not null,            -- วันทำการ (ก่อนตี 5 นับเป็นวันก่อนหน้า) คำนวณจากฝั่งแอป
  staff_id    bigint      references public.kpi_staff(id) on delete set null,
  device      text,
  created_at  timestamptz not null default now()
);

create table if not exists public.kpi_scores (
  id             bigint generated by default as identity primary key,
  response_id    bigint   not null references public.kpi_responses(id) on delete cascade,
  department_id  bigint   not null references public.kpi_departments(id) on delete cascade,
  score          smallint not null check (score between 1 and 5)
);

create index if not exists kpi_responses_branch_date_idx on public.kpi_responses (branch, biz_date);
create index if not exists kpi_responses_staff_idx       on public.kpi_responses (staff_id);
create index if not exists kpi_scores_response_idx       on public.kpi_scores (response_id);
create index if not exists kpi_scores_department_idx     on public.kpi_scores (department_id);

-- ---------- RLS (anon ใช้งานได้ เหมือนระบบ JJ อื่น ๆ) ----------
alter table public.kpi_departments enable row level security;
alter table public.kpi_staff       enable row level security;
alter table public.kpi_responses   enable row level security;
alter table public.kpi_scores      enable row level security;

drop policy if exists kpi_departments_all on public.kpi_departments;
create policy kpi_departments_all on public.kpi_departments for all using (true) with check (true);

drop policy if exists kpi_staff_all on public.kpi_staff;
create policy kpi_staff_all on public.kpi_staff for all using (true) with check (true);

drop policy if exists kpi_responses_all on public.kpi_responses;
create policy kpi_responses_all on public.kpi_responses for all using (true) with check (true);

drop policy if exists kpi_scores_all on public.kpi_scores;
create policy kpi_scores_all on public.kpi_scores for all using (true) with check (true);

grant select, insert, update, delete
  on public.kpi_departments, public.kpi_staff, public.kpi_responses, public.kpi_scores
  to anon, authenticated;

grant usage, select
  on sequence public.kpi_departments_id_seq, public.kpi_staff_id_seq,
              public.kpi_responses_id_seq,   public.kpi_scores_id_seq
  to anon, authenticated;

-- ---------- Views สำหรับสรุปผล ----------
-- รายวัน × แผนก (จำนวน, ค่าเฉลี่ย, การกระจาย 1–5)
create or replace view public.kpi_daily as
select r.branch,
       r.biz_date,
       s.department_id,
       count(*)::int                                   as n,
       round(avg(s.score)::numeric, 3)                 as avg_score,
       (count(*) filter (where s.score = 1))::int      as n1,
       (count(*) filter (where s.score = 2))::int      as n2,
       (count(*) filter (where s.score = 3))::int      as n3,
       (count(*) filter (where s.score = 4))::int      as n4,
       (count(*) filter (where s.score = 5))::int      as n5
from public.kpi_scores s
join public.kpi_responses r on r.id = s.response_id
group by r.branch, r.biz_date, s.department_id;

-- จำนวนลูกค้าที่กดให้คะแนน รายวัน
create or replace view public.kpi_daily_responses as
select branch,
       biz_date,
       count(*)::int         as n_responses,
       count(staff_id)::int  as n_with_staff
from public.kpi_responses
group by branch, biz_date;

-- คะแนนโหวตพนักงาน รายวัน
create or replace view public.kpi_staff_daily as
select branch, biz_date, staff_id, count(*)::int as votes
from public.kpi_responses
where staff_id is not null
group by branch, biz_date, staff_id;

-- รายเดือน × แผนก
create or replace view public.kpi_monthly as
select branch,
       to_char(biz_date, 'YYYY-MM')                              as ym,
       department_id,
       sum(n)::int                                               as n,
       round((sum(avg_score * n) / nullif(sum(n), 0))::numeric, 3) as avg_score,
       sum(n1)::int as n1, sum(n2)::int as n2, sum(n3)::int as n3,
       sum(n4)::int as n4, sum(n5)::int as n5
from public.kpi_daily
group by branch, to_char(biz_date, 'YYYY-MM'), department_id;

grant select on public.kpi_daily, public.kpi_daily_responses,
                public.kpi_staff_daily, public.kpi_monthly
  to anon, authenticated;

-- ---------- RPC: บันทึก 1 การให้คะแนน (response + scores) ใน transaction เดียว ----------
create or replace function public.kpi_submit(
  p_branch      text,
  p_biz_date    date,
  p_staff_id    bigint,
  p_device      text,
  p_created_at  timestamptz,
  p_scores      jsonb          -- [{"department_id":1,"score":5}, ...]
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  rid bigint;
begin
  insert into kpi_responses (branch, biz_date, staff_id, device, created_at)
  values (p_branch, p_biz_date, p_staff_id, p_device, coalesce(p_created_at, now()))
  returning id into rid;

  insert into kpi_scores (response_id, department_id, score)
  select rid,
         (e->>'department_id')::bigint,
         (e->>'score')::smallint
  from jsonb_array_elements(coalesce(p_scores, '[]'::jsonb)) e
  where (e->>'score')::int between 1 and 5;

  return rid;
end
$$;

grant execute on function public.kpi_submit(text, date, bigint, text, timestamptz, jsonb)
  to anon, authenticated;

-- ---------- ข้อมูลเริ่มต้น: แผนก (ใส่ให้เฉพาะตอนตารางว่าง แก้ได้ในหน้า "ตั้งค่า") ----------
insert into public.kpi_departments (name, icon, sort_order)
select d.name, d.icon, d.sort_order
from (values
  ('อาหาร',               '🍖', 1),
  ('บริการ',              '🙋', 2),
  ('ความสะอาด',           '🧹', 3),
  ('ต้อนรับ / แคชเชียร์', '🧾', 4)
) as d(name, icon, sort_order)
where not exists (select 1 from public.kpi_departments);

notify pgrst, 'reload schema';
