-- jjmk-access.sql — ระบบสิทธิ์กลาง (JJ Access) — รันครั้งเดียวใน Supabase SQL Editor (รันซ้ำได้ ไม่ลบข้อมูลเดิม)
-- ใช้บัญชี pnl_users ชุดเดิมเป็นบัญชีกลาง แล้วเพิ่ม "แผนสิทธิ์รายแอพ" ลงคอลัมน์ apps
--
-- โครงสร้างคอลัมน์ apps (jsonb) — คีย์ = รหัสแอพ, ค่า = แผนสิทธิ์รายหน้าจอ
--   {"pnl":{"dash":"v","income":"vae","exp":"vaed"}, "stock":{"count":"vae"}}
--   ตัวอักษรสิทธิ์: v=เห็นหน้า · a=เพิ่มข้อมูล · e=แก้ไข · d=ลบ
--   ไม่มีคีย์แอพ / ค่าว่าง = เข้าแอพนั้นไม่ได้เลย (ซ่อนจากหน้าศูนย์รวมแอพด้วย)
--   role='admin' = ทุกสิทธิ์ทุกแอพเสมอ (ไม่ต้องดู apps)

-- 1) คอลัมน์แผนสิทธิ์รายแอพ ----------------------------------------------------
alter table pnl_users add column if not exists apps jsonb not null default '{}'::jsonb;

-- 2) ข้อมูลประกอบบัญชี (ไว้โชว์ในหน้าจัดการผู้ใช้กลาง) --------------------------
alter table pnl_users add column if not exists note text default '';
alter table pnl_users add column if not exists branches jsonb not null default '[]'::jsonb;  -- สาขาที่ดูแล ([] = ทุกสาขา)
alter table pnl_users add column if not exists last_login timestamptz;

-- 3) ตารางบันทึกการเปลี่ยนสิทธิ์ (ใครแก้สิทธิ์ใครเมื่อไหร่) ---------------------
create table if not exists pnl_access_log (
  id bigint generated by default as identity primary key,
  actor text not null,              -- คนที่กดแก้ (username)
  target_user text not null,        -- บัญชีที่ถูกแก้
  action text not null,             -- เช่น 'แก้สิทธิ์', 'เพิ่มผู้ใช้', 'ปิดใช้งาน'
  detail text default '',
  created_at timestamptz default now()
);

-- 4) สิทธิ์ตาราง (แบบเดียวกับตาราง pnl_* เดิม: แอพเข้าผ่าน anon key) -------------
do $$ declare tb text; begin
  foreach tb in array array['pnl_access_log'] loop
    execute format('alter table %I enable row level security', tb);
    if not exists (select 1 from pg_policies where tablename=tb and policyname=tb||'_all') then
      execute format('create policy %I on %I for all to anon, authenticated using (true) with check (true)', tb||'_all', tb);
    end if;
    execute format('grant select, insert, update, delete on %I to anon, authenticated', tb);
  end loop;
end $$;
grant usage, select on all sequences in schema public to anon, authenticated;

-- 5) เปิดให้หน้าจัดการผู้ใช้กลาง "อ่าน" บัญชีของระบบที่ยังแยกอยู่ (อ่านอย่างเดียว) -----
--    sc_users  = ระบบนับสต๊อก
--    app_users = ครัวกลาง + ซ่อมบำรุง (โปรไฟล์ของ Supabase Auth)
--    ใช้ตอน "นำเข้าบัญชีเดิม" — ตารางไหนไม่มีในโปรเจกต์นี้ ข้ามไปเงียบๆ
--    ⚠️ ให้แค่สิทธิ์ SELECT — ไม่ให้เพิ่ม/แก้/ลบ ระบบเดิมจึงทำงานเหมือนเดิมทุกอย่าง
do $$ declare t text; begin
  foreach t in array array['sc_users','app_users'] loop
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name=t) then
      execute format('grant select on %I to anon, authenticated', t);
      if not exists (select 1 from pg_policies where tablename=t and policyname=t||'_read_central') then
        execute format('create policy %I on %I for select to anon, authenticated using (true)', t||'_read_central', t);
      end if;
    end if;
  end loop;
end $$;

-- 6) ให้บัญชี admin ที่มีอยู่แล้วได้สิทธิ์เต็มทุกแอพโดยอัตโนมัติ ------------------
--    (admin ไม่ต้องพึ่ง apps อยู่แล้ว — ตั้งไว้ให้หน้าจัดการโชว์เครื่องหมายถูกครบ)
update pnl_users set apps = '{
  "pnl":{"dash":"vaed","income":"vaed","exp":"vaed","detail":"vaed","vatrep":"vaed","usage":"vaed","ck":"vaed","sum":"vaed","recon":"vaed","pv":"vaed","etc":"vaed","set":"vaed"},
  "owner":{"overview":"vaed","pl":"vaed","manual":"vaed","inst":"vaed"},
  "kpi":{"dash":"vaed","kiosk":"vaed"},
  "payroll":{"today":"vaed","emp":"vaed","payroll":"vaed","detail":"vaed","shift":"vaed","cal":"vaed","holi":"vaed","adv":"vaed","loan":"vaed","dep":"vaed","sso":"vaed","mou":"vaed","audit":"vaed","settings":"vaed"},
  "stock":{"dash":"vaed","count":"vaed","order":"vaed","link":"vaed","set":"vaed","sched":"vaed","items":"vaed","cfg":"vaed"},
  "maint":{"sched":"vaed","log":"vaed","tasks":"vaed"},
  "kitchen":{"today":"vaed","dash":"vaed","plan":"vaed","buy":"vaed","produce":"vaed","orders":"vaed","stock":"vaed","menus":"vaed","items":"vaed","stats":"vaed","acc":"vaed","set":"vaed"},
  "social":{"dash":"vaed","feed":"vaed","chat":"vaed","insight":"vaed","bot":"vaed","ch":"vaed","set":"vaed"},
  "invoice":{"new":"vaed","list":"vaed","history":"vaed","cancelled":"vaed","failed":"vaed","settings":"vaed"},
  "calendar":{"month":"vaed","agenda":"vaed","sync":"vaed"},
  "admin":{"users":"vaed","log":"vaed"}
}'::jsonb
where role='admin' and (apps is null or apps = '{}'::jsonb);

-- 7) บัญชีพนักงานเดิมที่ยังไม่เคยตั้งสิทธิ์รายแอพ -------------------------------
--    แปลง perms เดิมของระบบ P&L (edit/view/none) มาเป็นแผนสิทธิ์แอพ pnl ให้อัตโนมัติ
--    ระบบอื่นเว้นว่างไว้ = เข้าไม่ได้ จนกว่า admin จะติ๊กเปิดในหน้าจัดการผู้ใช้กลาง
update pnl_users u
set apps = jsonb_build_object('pnl', (
  select coalesce(jsonb_object_agg(k, case when val='edit' then 'vaed' when val='view' then 'v' else '' end), '{}'::jsonb)
  from (select key as k, perms->>key as val from jsonb_object_keys(coalesce(u.perms,'{}'::jsonb)) as key) t
  where val in ('edit','view')
))
where role <> 'admin' and (apps is null or apps = '{}'::jsonb) and perms is not null and perms <> '{}'::jsonb;

-- เสร็จแล้ว: เปิดหน้า https://thananant.github.io/JJ-PnL/jjmk-admin.html ด้วยบัญชี admin
-- เพื่อดูบัญชีทั้งหมด · ติ๊กเลือกแอพที่แต่ละคนเข้าได้ · ตั้งสิทธิ์ ซ่อน/ดู/เพิ่ม/แก้/ลบ รายหน้าจอ
