-- =====================================================================
--  JJ Invoice · ระบบออกใบกำกับภาษี (จริงใจหมูกระทะ)
--  Supabase project: aikyxvluaiubdidqxwnd · table prefix: inv_
--  รันซ้ำได้ (idempotent) — รันทั้งไฟล์ใน SQL Editor
--
--  หลักการเก็บข้อมูล: เก็บเฉพาะตัวหนังสือ — ไม่มีไฟล์รูป/PDF ใดๆ ใน Supabase
--  (ไฟล์ PDF บิลเก็บลงโฟลเดอร์ NAS ผ่านเบราว์เซอร์ · ลายเซ็นเก็บในเครื่อง)
--
--  ระบบล็อกอินใช้ตาราง pnl_users ร่วมกับระบบ P&L (ไม่ได้สร้างในไฟล์นี้ —
--  ต้องรัน jjmk_pnl_users.sql ของระบบ P&L ก่อน ถ้ายังไม่เคยรัน)
-- =====================================================================

-- ---------- ตาราง ----------

-- เลขบิลรันต่อสาขา (last_no = เลขล่าสุดที่ใช้แล้ว · ใบต่อไป = +1)
create table if not exists public.inv_counters (
  prefix   text primary key,           -- JJRD / JJLP
  last_no  integer not null default 0
);

create table if not exists public.inv_invoices (
  id             bigint generated by default as identity primary key,
  bill_no        text not null unique,              -- เช่น JJRD1006
  branch_prefix  text not null,
  issued_at      timestamptz not null default now(),
  customer_name  text,
  tax_id         text,
  phone          text,
  email          text,
  address        text,
  items          jsonb not null default '[]'::jsonb,
  gross          numeric(12,2) not null default 0,  -- รวมทั้งสิ้น (รวม VAT)
  discount       numeric(12,2) not null default 0,
  net            numeric(12,2) not null default 0,  -- มูลค่าสุทธิก่อน VAT
  vat            numeric(12,2) not null default 0,
  grand_total    numeric(12,2) not null default 0,
  payment_method text,
  status         text not null default 'ออกแล้ว',    -- ออกแล้ว / ยกเลิก
  status_detail  text,
  nas_path       text,                               -- ที่เก็บไฟล์ใน NAS เช่น 2026-09/JJRD1006.pdf
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists inv_invoices_branch_idx on public.inv_invoices (branch_prefix, issued_at desc);
create index if not exists inv_invoices_status_idx on public.inv_invoices (status);

-- v2: สถานะการส่งอีเมล (ส่งผ่าน Apps Script ของ Gmail ร้าน + ตรวจการตีกลับ)
alter table public.inv_invoices add column if not exists email_status text;
alter table public.inv_invoices add column if not exists email_status_detail text;
alter table public.inv_invoices add column if not exists email_sent_at timestamptz;
alter table public.inv_invoices add column if not exists resend_count integer not null default 0;

-- v3: บันทึกว่าใครทำรายการ (ล็อกอินด้วยบัญชี pnl_users)
alter table public.inv_invoices add column if not exists created_by text;
alter table public.inv_invoices add column if not exists updated_by text;

-- v2: ตั้งค่าที่ใช้ร่วมกันทุกเครื่อง (เช่น gas_endpoint = URL ตัวส่งอีเมล)
create table if not exists public.inv_settings (
  key   text primary key,
  value text
);

-- v3: ประวัติการใช้งาน — ใครทำอะไรเมื่อไหร่ (append-only จากแอป)
create table if not exists public.inv_activity (
  id        bigint generated by default as identity primary key,
  at        timestamptz not null default now(),
  user_name text,
  action    text not null,   -- ออกบิล / แก้ไขบิล / ยกเลิกบิล / เรียกคืนบิล / ส่งอีเมล / ...
  bill_no   text,
  detail    text
);
create index if not exists inv_activity_at_idx on public.inv_activity (at desc);

-- ---------- ตั้งเลขบิลต่อจากระบบเดิม (มีแถวอยู่แล้วจะไม่ทับ) ----------
-- JJRD ใช้ถึง 1005 (ใบต่อไป 1006) · JJLP เริ่ม 1001
insert into public.inv_counters (prefix, last_no) values ('JJRD', 1005), ('JJLP', 1000)
  on conflict (prefix) do nothing;

-- ---------- RPC ออกเลขบิลแบบ atomic (กันเลขซ้ำ) ----------
-- p_start = เลขบิลใบแรกที่จะออก ถ้ายังไม่มีแถว counter ของสาขานั้น
create or replace function public.inv_next_bill_no(p_prefix text, p_start integer default 1)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_no integer;
begin
  insert into public.inv_counters as c (prefix, last_no)
  values (p_prefix, greatest(p_start, 1))
  on conflict (prefix) do update set last_no = c.last_no + 1
  returning last_no into v_no;
  return p_prefix || lpad(v_no::text, 4, '0');
end;
$$;

-- ---------- RLS (anon ใช้งานได้ เหมือนระบบ JJ อื่น ๆ) ----------
alter table public.inv_counters enable row level security;
alter table public.inv_invoices enable row level security;
alter table public.inv_settings enable row level security;
alter table public.inv_activity enable row level security;

drop policy if exists inv_counters_all on public.inv_counters;
create policy inv_counters_all on public.inv_counters for all using (true) with check (true);

drop policy if exists inv_invoices_all on public.inv_invoices;
create policy inv_invoices_all on public.inv_invoices for all using (true) with check (true);

drop policy if exists inv_settings_all on public.inv_settings;
create policy inv_settings_all on public.inv_settings for all using (true) with check (true);

drop policy if exists inv_activity_all on public.inv_activity;
create policy inv_activity_all on public.inv_activity for all using (true) with check (true);

grant select, insert, update, delete
  on public.inv_counters, public.inv_invoices, public.inv_settings
  to anon, authenticated;

-- ประวัติการใช้งานเป็น append-only จากฝั่งแอป: อ่าน + เพิ่มได้เท่านั้น (แก้/ลบไม่ได้)
grant select, insert on public.inv_activity to anon, authenticated;

grant usage, select on sequence public.inv_invoices_id_seq to anon, authenticated;
grant usage, select on sequence public.inv_activity_id_seq to anon, authenticated;

grant execute on function public.inv_next_bill_no(text, integer) to anon, authenticated;
