-- jjmk_owner_setup.sql — ติดตั้งระบบ Owner (หน้า jjmk-owner.html) — รันครั้งเดียวใน Supabase SQL Editor
-- ตารางการผ่อนชำระ (สินเชื่อ/ผ่อนอุปกรณ์/เงินกู้ของกิจการ)
-- สิทธิ์ตามแบบตาราง pnl_* เดิม: แอพเขียนผ่าน anon key (หน้า Owner เปิดได้เฉพาะบัญชี admin ของระบบ P&L)

create table if not exists pnl_installments (
  id bigint generated by default as identity primary key,
  name text not null,                      -- ชื่อรายการ เช่น "ผ่อนรถส่งของ"
  lender text default '',                  -- ผู้ให้กู้ / ธนาคาร
  branch text,                             -- รหัสสาขา (null = กิจการรวม)
  monthly_amount numeric not null,         -- ค่างวด/เดือน
  months_total integer not null,           -- จำนวนงวดทั้งหมด
  start_month text not null,               -- งวดแรก 'YYYY-MM'
  total_amount numeric,                    -- ยอดรวมสัญญา (null = ค่างวด × จำนวนงวด)
  months_paid integer,                     -- จ่ายแล้วกี่งวด (null = นับอัตโนมัติจากเดือนปัจจุบัน)
  paid_extra numeric default 0,            -- เงินโปะเพิ่มนอกเหนือค่างวด
  note text default '',
  active boolean default true,             -- false = ปิดสัญญา/ย้ายไปประวัติ
  created_at timestamptz default now()
);

alter table pnl_installments enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where tablename='pnl_installments' and policyname='pnl_inst_all') then
    create policy pnl_inst_all on pnl_installments for all to anon, authenticated
      using (true) with check (true);
  end if;
end $$;
grant select, insert, update, delete on pnl_installments to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
