-- jjmk_owner_setup.sql — ติดตั้งระบบ Owner (หน้า jjmk-owner.html) — รันครั้งเดียวใน Supabase SQL Editor (รันซ้ำได้)
-- 1) pnl_installments   — การผ่อนชำระ (สินเชื่อ/ผ่อนอุปกรณ์/เงินกู้ของกิจการ)
-- 2) pnl_owner_monthly  — ยอดขาย/กำไรใส่เองรายเดือน (ตัวเลขมือชนะค่าคำนวณ)
-- สิทธิ์ตามแบบตาราง pnl_* เดิม: แอพเขียนผ่าน anon key (หน้า Owner เปิดได้เฉพาะบัญชี admin ของระบบ P&L)

create table if not exists pnl_installments (
  id bigint generated by default as identity primary key,
  name text not null,                      -- ชื่อรายการ เช่น "ผ่อนรถส่งของ"
  lender text default '',                  -- ผู้ให้กู้ / ธนาคาร
  branch text,                             -- รหัสสาขา (null = กิจการรวม)
  monthly_amount numeric not null,         -- ค่างวด/เดือน
  months_total integer not null,           -- จำนวนงวดทั้งหมด
  start_month text not null,               -- งวดแรก 'YYYY-MM'
  total_amount numeric,                    -- ยอดรวมสัญญา (null = ค่างวด × จำนวนงวด)
  months_paid integer,                     -- จ่ายแล้วกี่งวด (null = นับอัตโนมัติจากเดือนปัจจุบัน)
  paid_extra numeric default 0,            -- เงินโปะเพิ่มนอกเหนือค่างวด
  note text default '',
  active boolean default true,             -- false = ปิดสัญญา/ย้ายไปประวัติ
  created_at timestamptz default now()
);

-- ยอดขาย/กำไรใส่เองรายเดือน — เดือนไหนเจ้าของคีย์มือ หน้า Owner ใช้ตัวเลขนี้แทนค่าคำนวณ
create table if not exists pnl_owner_monthly (
  id bigint generated by default as identity primary key,
  branch text not null default 'ALL',      -- 'ALL' = ทั้งกิจการ หรือรหัสสาขา เช่น JJRD
  month text not null,                     -- 'YYYY-MM'
  sales numeric,                           -- ยอดขายใส่เอง (null = ใช้ค่าคำนวณจากระบบ)
  profit numeric,                          -- กำไรสุทธิใส่เอง (null = ใช้ค่าคำนวณจากระบบ)
  note text default '',
  updated_at timestamptz default now(),
  unique (branch, month)                   -- ให้ upsert ทับเดือนเดิมได้
);

do $$ declare tb text; begin
  foreach tb in array array['pnl_installments','pnl_owner_monthly'] loop
    execute format('alter table %I enable row level security', tb);
    -- ('pnl_inst_all' = ชื่อ policy จากสคริปต์เวอร์ชันแรก — ถ้ามีแล้วไม่สร้างซ้ำ)
    if not exists (select 1 from pg_policies where tablename=tb and policyname in (tb||'_all','pnl_inst_all')) then
      execute format('create policy %I on %I for all to anon, authenticated using (true) with check (true)', tb||'_all', tb);
    end if;
    execute format('grant select, insert, update, delete on %I to anon, authenticated', tb);
  end loop;
end $$;
grant usage, select on all sequences in schema public to anon, authenticated;
