-- ============================================================
-- jj_audit.sql — ระบบล็อกอิน + ประวัติการทำรายการ (audit log)
-- ล็อกอินใช้บัญชีเดียวกับแอป P&L (ตาราง pnl_users ที่มีอยู่แล้ว — ไฟล์นี้ไม่แตะ)
-- ตารางนี้เก็บว่า "ใคร" เพิ่ม/แก้ไข/ลบ อะไร เมื่อไหร่ ในระบบเงินเดือน
-- รันทั้งไฟล์ใน Supabase SQL Editor (Ctrl+A ก่อน Run) · รันซ้ำได้ ไม่พัง
-- ============================================================

CREATE TABLE IF NOT EXISTS payroll_audit (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     text NOT NULL DEFAULT '',
  display_name text NOT NULL DEFAULT '',
  action       text NOT NULL DEFAULT '',
  tbl          text NOT NULL DEFAULT '',
  detail       text NOT NULL DEFAULT '',
  page         text NOT NULL DEFAULT '',
  at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payroll_audit_id_idx ON payroll_audit (id DESC);

ALTER TABLE payroll_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS payroll_audit_all ON payroll_audit;

CREATE POLICY payroll_audit_all ON payroll_audit FOR ALL USING (true) WITH CHECK (true);

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE payroll_audit;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
