-- ============================================================
-- jj_deposit.sql — ระบบเงินประกันพนักงาน (JJ-Payroll)
-- รันทั้งไฟล์ใน Supabase SQL Editor (โปรเจกต์ jjmk-stock) ครั้งเดียว
-- รันซ้ำได้ ไม่พัง
-- ============================================================

-- 1) คอลัมน์ตั้งค่ารายคนในตาราง employees
ALTER TABLE employees ADD COLUMN IF NOT EXISTS deposit_target  numeric NOT NULL DEFAULT 5000;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS deposit_monthly numeric NOT NULL DEFAULT 500;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS deposit_opening numeric NOT NULL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS deposit_on      boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN employees.deposit_target  IS 'เป้าหมายเงินประกันรวม (บาท)';
COMMENT ON COLUMN employees.deposit_monthly IS 'หักต่อเดือนโดยอัตโนมัติ (บาท)';
COMMENT ON COLUMN employees.deposit_opening IS 'ยอดที่เก็บมาก่อนเริ่มใช้ระบบ — คนเก็บครบแล้วใส่เท่าเป้าหมาย';
COMMENT ON COLUMN employees.deposit_on      IS 'เปิด/ปิดการหักเงินประกันของคนนี้';

-- 2) ตาราง override รายงวด (แก้จำนวนหักเฉพาะงวด / งดหักงวดนั้น)
CREATE TABLE IF NOT EXISTS deposit_entries (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  period      text NOT NULL,
  amount      numeric NOT NULL DEFAULT 0,
  note        text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, period)
);

-- 3) RLS แบบเดียวกับตารางอื่นของระบบ
ALTER TABLE deposit_entries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'deposit_entries' AND policyname = 'deposit_entries_all'
  ) THEN
    CREATE POLICY deposit_entries_all ON deposit_entries
      FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;

-- 4) เปิด realtime ให้หน้าเว็บ sync สด
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE deposit_entries;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
END
$$;
