// เทสข้อมูลพนักงานเพิ่ม (jj_employee_hr.sql) กับโค้ดจริงใน jjmk-payroll.html
const fs=require('fs');
const { JSDOM, VirtualConsole } = require('jsdom');
const html=fs.readFileSync(__dirname+'/../../jjmk-payroll.html','utf8').replace(/<script src="[^"]+"><\/script>/g,'').replace(/<link[^>]+>/g,'');
const vc=new VirtualConsole(); const errs=[]; vc.on('jsdomError',e=>errs.push(e.message));
const writes=[];
function chain(table){ let op='select', row=null; const b={};
  for(const m of ['select','eq','neq','gte','lte','lt','gt','in','is','not','or','order','limit','range','single','maybeSingle','on','subscribe']) b[m]=()=>b;
  for(const m of ['insert','update','upsert','delete']) b[m]=(r)=>{ op=m; row=r; return b; };
  b.then=(ok,er)=>{ if(op!=='select') writes.push({table,op,row}); return Promise.resolve({data: op==='insert'?Object.assign({id:99},row):[],error:null}).then(ok,er); };
  return b; }
const dom=new JSDOM(html,{url:'https://thananant.github.io/JJ-PnL/jjmk-payroll.html',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,
  beforeParse(w){ w.supabase={createClient:()=>({from:t=>chain(t),channel:()=>chain('ch'),rpc:()=>chain('rpc'),removeChannel(){},storage:{from:()=>({})}})}; w.TextEncoder=require('util').TextEncoder; w.alert=()=>{}; w.confirm=()=>true; w.indexedDB=undefined; w.scrollTo=()=>{}; }});
const w=dom.window, d=w.document; const E=s=>w.eval(s);
let fail=0; const ok=(c,m)=>{console.log((c?'  ✓ ':'  ✗ ')+m); if(!c) fail++;};
const tick=()=>new Promise(r=>setTimeout(r,30));
setTimeout(async ()=>{ try{
  const plus=n=>E(`(()=>{ const x=new Date(bizToday()+'T12:00:00'); x.setDate(x.getDate()+(${n})); return localYMD(x); })()`);
  console.log('[อ่าน/เขียนฐานข้อมูล]');
  const row={id:1,code:'A',nick:'แพร',full_name:'แพรวา',branch:'JJRD',dept:'หน้าร้าน',position:'เสิร์ฟ',wage_type:'daily',rate:450,active:true,
    gender:'หญิง',nationality:'MM',address:'12/3 ซอยลาดพร้าว',emergency_name:'สมศรี',emergency_relation:'แม่',emergency_phone:'0811111111',
    passport_exp:plus(30),work_permit_exp:plus(200),pink_card_exp:plus(-5),doc_notify_in:true,doc_notify_out:false,doc_guardian:false,
    sso_hospital:'รพ.ลาดพร้าว',face_scan:true,worker_group:'mou',doc_status:'passport',doc_start:'2026-09-01',doc_done:'',doc_agency:'บริษัท โกลด์สตาร์ อินฟินิตี้ จำกัด (Aisoon)'};
  w.__row=row;
  E(`applyUser({role:'owner'}); hrReady=true; empInfoReady=true; ssoReady=true; kbizReady=true; employees=[fromDbEmp(window.__row),
     fromDbEmp({id:2,code:'B',nick:'บอส',branch:'JJRD',wage_type:'daily',rate:450,active:true}),
     fromDbEmp({id:3,code:'C',nick:'ต้น',branch:'JJRD',wage_type:'daily',rate:450,active:false,passport_exp:'${plus(-30)}'}),
     fromDbEmp({id:4,code:'D',nick:'มิว',branch:'JJLP',wage_type:'daily',rate:450,active:true,birth_date:'${plus(-365*16)}',nationality:'MM',worker_group:'',doc_status:'mou'})];
     recomputeAll();`);
  const e1=()=>E(`employees[0]`);
  ok(E(`employees[0].nat`)==='MM' && E(`employees[0].emgRel`)==='แม่' && E(`employees[0].faceScan`)===true && E(`employees[0].group`)==='mou','fromDbEmp อ่านช่องใหม่ครบ');
  const db1=E(`JSON.stringify(toDbEmp(employees[0]))`);
  ok(/"nationality":"MM"/.test(db1) && /"doc_agency":"บริษัท โกลด์สตาร์/.test(db1) && /"doc_done":null/.test(db1),'toDbEmp เขียนช่องใหม่ (วันที่ว่าง = null) เมื่อรัน SQL แล้ว');
  E(`hrReady=false`); const db0=E(`JSON.stringify(toDbEmp(employees[0]))`); E(`hrReady=true`);
  ok(!/nationality|passport_exp|worker_group/.test(db0),'ยังไม่รัน SQL = ไม่ส่งช่องใหม่ (บันทึกพนักงานไม่พัง)');
  console.log('[เตือนเอกสารหมดอายุ (3 เดือน)]');
  const al=JSON.parse(E(`JSON.stringify(docAlerts(employees[0]))`));
  ok(al.length===2 && al.find(a=>a.k==='passExp').days===30 && al.find(a=>a.k==='pinkExp').expired,'Passport เหลือ 30 วัน + บัตรชมพูหมดแล้ว = เตือน · ใบอนุญาต 200 วัน = ไม่เตือน');
  ok(E(`docAlerts(employees[2]).length`)===0,'คนพ้นสภาพ = ไม่เตือน');
  ok(E(`docAlertText(docAlerts(employees[0]).find(a=>a.expired))`)==='บัตรชมพู หมดอายุแล้ว 5 วัน','ข้อความเตือนอ่านง่าย');
  console.log('[หน้ารวมการ์ด]');
  E(`detailList()`);
  const txt=()=>d.getElementById('detailContent').textContent;
  ok(/เอกสารหมดอายุ\/ใกล้หมดใน 3 เดือน 1 คน/.test(txt()),'แถบเตือนบนหน้ารวม นับเฉพาะคนที่ยังทำงาน');
  const card=n=>[...d.querySelectorAll('.dt-card')].find(c=>c.querySelector('.dt-nm b').textContent===n);
  ok(card('แพร').querySelector('.dt-doc.bad') && /\+1/.test(card('แพร').querySelector('.dt-doc').textContent) && /MOU/.test(card('แพร').textContent),'การ์ดมีบรรทัดเตือนเอกสาร (แดง เมื่อมีใบหมดแล้ว) + ป้ายกลุ่ม');
  d.getElementById('detailActive').value='docexp'; E(`renderDetail()`);
  ok(d.querySelectorAll('.dt-card').length===1,'ตัวกรอง "เอกสารหมด/ใกล้หมด"');
  d.getElementById('detailActive').value='1'; d.getElementById('detailGroup').value='proc'; E(`renderDetail()`);
  ok(d.querySelectorAll('.dt-card').length===2,'ตัวกรอง "กำลังทำเอกสาร"');
  d.getElementById('detailGroup').value='general'; E(`renderDetail()`);
  ok([...d.querySelectorAll('.dt-card .dt-nm b')].map(b=>b.textContent).sort().join()==='บอส,มิว','ตัวกรอง "ทั่วไป" = ไม่ได้ตั้งกลุ่ม');
  d.getElementById('detailGroup').value=''; E(`renderDetail()`);
  console.log('[แท็บข้อมูลส่วนตัว]');
  E(`openDetail(1); setDetailTab('info')`);
  const info=txt();
  ok(['รายละเอียด','เอกสาร','ประกันสังคม','การจ่ายเงินเดือน','สแกนหน้า · กลุ่ม','การทำเอกสาร'].every(h=>[...d.querySelectorAll('.dt-h4')].some(x=>x.firstChild.textContent===h)),'แบ่งหัวข้อตามที่เจ้าของให้มา');
  ok(/พม่า/.test(info) && /สมศรี \(แม่\) 0811111111/.test(info) && /รพ\.ลาดพร้าว/.test(info) && /เหลือ 30 วัน/.test(info) && /หมดอายุแล้ว 5 วัน/.test(info) && /กำลังทำ Passport/.test(info) && /Aisoon/.test(info) && /เพิ่มแล้ว/.test(info),'แสดงค่าครบ: สัญชาติ · ผู้ติดต่อฉุกเฉิน · รพ. · วันหมดอายุ · การทำเอกสาร · สแกนหน้า');
  const expBadge=E(`missingPersonal(employees[0]).length + docAlerts(employees[0]).length`);
  ok(expBadge>=2 && [...d.querySelectorAll('.dt-tabs button')].find(b=>/ข้อมูลส่วนตัว/.test(b.textContent)).querySelector('.dt-badge').textContent===String(expBadge),'ป้ายแดงบนแท็บ = ข้อมูลขาด + เอกสารที่ต้องดู ('+expBadge+')');
  E(`setDetailTab('over')`);
  ok(/📄 เอกสาร:/.test(txt()) && /กำลังทำ Passport/.test(txt()),'แท็บภาพรวมเตือนเอกสาร + บอกสถานะการทำเอกสาร');
  E(`openDetail(4); setDetailTab('info')`);
  ok(/ยังไม่มี — จำเป็น \(อายุไม่ถึง 18\)/.test(txt()),'อายุไม่ถึง 18 + ไม่มีหนังสือยินยอมผู้ปกครอง = เตือนแดง');
  E(`hrReady=false; renderDetail()`);
  ok(d.getElementById('empHrSqlBox') && /ALTER TABLE employees ADD COLUMN IF NOT EXISTS nationality/.test(d.getElementById('empHrSqlBox').value),'ยังไม่รัน SQL = มีปุ่ม/กล่องคัดลอก SQL ในแท็บ');
  E(`hrReady=true`);
  console.log('[ฟอร์ม ✎ = ข้อมูลการทำงานอย่างเดียว]');
  E(`go('emp'); openEmpForm(4)`);
  ok(['fBirth','fPhone','fBank','fSso','fNat','fAddr','fPassExp','fGroup','fDocStatus','fFace'].every(id=>!d.getElementById(id)),'ฟอร์มไม่มีช่องข้อมูลส่วนตัวแล้ว');
  ok(/แก้ที่แท็บ/.test(d.getElementById('fInfoNote').textContent) && /ไปที่ข้อมูลส่วนตัว/.test(d.getElementById('fInfoBtnWrap').textContent),'ฟอร์มบอกว่าข้อมูลส่วนตัวแก้ที่ไหน + ปุ่มพาไป');
  d.getElementById('fNick').value='มิวมิว';
  writes.length=0; await w.eval(`saveEmpForm()`); await tick();
  const up=writes.find(x=>x.table==='employees'&&x.op==='update');
  const PCOLS=['birth_date','phone','bank_name','bank_account','bank_account_name','kbiz_added','sso_on','sso_id','gender','nationality','address','emergency_name','passport_exp','doc_guardian','face_scan','worker_group','doc_status','doc_start','doc_agency'];
  ok(up && up.row.nick==='มิวมิว' && PCOLS.every(c=>!(c in up.row)),'บันทึกฟอร์ม ✎ ไม่ส่งคอลัมน์ข้อมูลส่วนตัว (ไม่ทับที่แก้ในแท็บ)');
  ok(E(`employees.find(e=>e.id===4).nat`)==='MM' && E(`employees.find(e=>e.id===4).docStatus`)==='mou' && E(`employees.find(e=>e.id===4).nick`)==='มิวมิว','ข้อมูลส่วนตัวในเครื่องยังอยู่ครบ');
  console.log('[แก้ข้อมูลส่วนตัวในแท็บ]');
  let toasts=[]; w.toast=m=>toasts.push(m);
  E(`openDetailInfo(4)`);
  ok(E(`curPage()`)==='detail' && E(`detailTab`)==='info' && d.querySelectorAll('.dt-h4 .dt-ed').length===7,'openDetailInfo → แท็บข้อมูลส่วนตัว · ✎ ทุกหัวข้อ + ⚙️ ที่หัวข้อการทำงาน');
  ok(/อายุ 1[0-9] ปี \(ไม่ถึง 18\)/.test(d.getElementById('dtHrHints').textContent) && /หนังสือยินยอมผู้ปกครอง/.test(d.getElementById('dtHrHints').textContent),'คำแนะนำ: อายุไม่ถึง 18 → กลุ่มคนเถื่อน + หนังสือผู้ปกครอง');
  const btnSec=t=>[...d.querySelectorAll('.dt-h4')].find(h=>h.firstChild.textContent===t).querySelector('button');
  btnSec('รายละเอียด').click();
  ok(d.getElementById('dtEditForm') && d.getElementById('pi_gender') && d.getElementById('pi_address') && d.getElementById('pi_birth') && !d.getElementById('pi_passExp'),'กด ✎ หัวข้อ = เปิดฟอร์มเฉพาะหัวข้อนั้น');
  ok(d.getElementById('pi_nat').value==='MM' && d.getElementById('pi_emgRel_l'),'ฟอร์มเติมค่าเดิม + มีตัวเลือกความสัมพันธ์');
  d.getElementById('pi_gender').value='หญิง'; d.getElementById('pi_address').value='99 ถ.รัชดา';
  d.getElementById('pi_address').dispatchEvent(new w.Event('input',{bubbles:true}));
  ok(/99 ถ\.รัชดา/.test(w.sessionStorage.getItem('jjpay_pidraft')||''),'ร่างที่กรอกค้างเก็บใน sessionStorage (ลากหน้าลงแล้วไม่หาย)');
  E(`renderAll()`);
  ok(d.getElementById('pi_address') && d.getElementById('pi_address').value==='99 ถ.รัชดา','ข้อมูลสด/รีเฟรชไม่วาดทับฟอร์มที่กำลังกรอก');
  writes.length=0; await w.eval(`saveInfo()`); await tick();
  let u=writes.filter(x=>x.table==='employees'&&x.op==='update');
  ok(u.length===1 && JSON.stringify(Object.keys(u[0].row).sort())==='["address","gender"]' && u[0].row.address==='99 ถ.รัชดา','บันทึกส่งเฉพาะช่องที่เปลี่ยนจริง');
  ok(E(`employees.find(e=>e.id===4).address`)==='99 ถ.รัชดา' && !d.getElementById('dtEditForm') && !w.sessionStorage.getItem('jjpay_pidraft'),'ข้อมูลในเครื่องอัปเดต · ปิดฟอร์ม · ล้างร่าง');
  btnSec('เอกสาร').click(); d.getElementById('pi_passExp').value=plus(10); d.getElementById('pi_docGuardian').checked=true;
  writes.length=0; await w.eval(`saveInfo()`); await tick();
  u=writes.find(x=>x.table==='employees'&&x.op==='update');
  ok(u && u.row.passport_exp===plus(10) && u.row.doc_guardian===true && Object.keys(u.row).length===2,'หัวข้อเอกสาร: วันหมดอายุ + ติ๊กหนังสือผู้ปกครอง');
  ok(!/หนังสือยินยอมผู้ปกครอง/.test(d.getElementById('dtHrHints').textContent) && /Passport ใกล้หมดอายุ|Passport/.test(d.getElementById('dtHrHints').textContent),'คำแนะนำอัปเดตตามข้อมูลใหม่');
  btnSec('เอกสาร').click(); d.getElementById('pi_passExp').value='';
  writes.length=0; await w.eval(`saveInfo()`); await tick();
  u=writes.find(x=>x.table==='employees'&&x.op==='update');
  ok(u && u.row.passport_exp===null,'ลบวันที่ = ส่ง null');
  btnSec('การทำเอกสาร').click(); d.getElementById('pi_docStart').value='2026-10-10'; d.getElementById('pi_docDone').value='2026-10-01';
  toasts=[]; writes.length=0; await w.eval(`saveInfo()`); await tick();
  ok(!writes.length && toasts.some(t=>/วันที่ทำเอกสารเสร็จ ต้องไม่ก่อนวันที่เริ่มทำ/.test(t)),'วันเสร็จก่อนวันเริ่ม = ไม่บันทึก');
  d.getElementById('pi_docStart').value='';d.getElementById('pi_docDone').value='';
  btnSec('ประกันสังคม').click();
  ok(d.getElementById('pi_ssoOn') && !d.getElementById('pi_docStart'),'สลับหัวข้อ (ถามก่อนทิ้งที่แก้ไว้) แล้วเปิดหัวข้อใหม่');
  toasts=[]; writes.length=0; await w.eval(`saveInfo()`); await tick();
  ok(!writes.length && toasts.includes('ไม่มีอะไรเปลี่ยน') && !d.getElementById('dtEditForm'),'ไม่ได้แก้อะไร = ไม่เขียนฐานข้อมูล');
  E(`piStart('all')`);
  ok(d.querySelectorAll('#dtEditForm .pi-form').length===6 && d.querySelector('.pi-bar') && !d.querySelector('.pi-act'),'✎ แก้ไขทั้งหมด = ทุกหัวข้อเป็นฟอร์ม + ปุ่มบันทึกเดียวด้านล่าง');
  d.getElementById('pi_faceScan').checked=true; d.getElementById('pi_group').value='illegal_minor'; d.getElementById('pi_bankName').value='เงินสด';
  writes.length=0; await w.eval(`saveInfo()`); await tick();
  u=writes.find(x=>x.table==='employees'&&x.op==='update');
  ok(u && JSON.stringify(Object.keys(u.row).sort())==='["bank_name","face_scan","worker_group"]' && u.row.face_scan===true,'บันทึกทั้งหมด ส่งเฉพาะที่เปลี่ยน');
  E(`piStart('detail')`); d.getElementById('pi_phone').value='0899999999';
  E(`setDetailTab('over')`);
  ok(E(`dtEditSec`)===null && E(`employees.find(e=>e.id===4).phone`)!=='0899999999','เปลี่ยนแท็บระหว่างแก้ = ถามแล้วทิ้ง');
  E(`hrReady=false; setDetailTab('info'); piStart('detail')`);
  ok(/jj_employee_hr\.sql/.test(d.getElementById('dtEditForm').textContent) && !d.getElementById('pi_gender') && d.getElementById('pi_phone'),'ยังไม่รัน SQL ของช่องไหน = ช่องนั้นบอกให้รัน SQL ไม่ให้กรอก');
  E(`piCancel(); renderDetail()`);
  ok([...d.querySelectorAll('.dt-h4')].find(h=>h.firstChild.textContent==='เอกสาร').querySelector('button')===null,'หัวข้อที่ทุกช่องยังไม่รัน SQL = ไม่มีปุ่ม ✎');
  E(`hrReady=true`);
  E(`applyUser({role:'staff',apps:{payroll:{detail:'v',emp:'vae'}}}); renderDetail(true)`);
  ok(!d.querySelector('.dt-h4 .dt-ed') && !/แก้ไขทั้งหมด/.test(d.getElementById('detailContent').textContent),'ไม่มีสิทธิ์แก้ไขหน้าข้อมูลพนักงาน = ดูอย่างเดียว');
  E(`piStart('detail')`);
  ok(!d.getElementById('dtEditForm'),'piStart ไม่ทำงานถ้าไม่มีสิทธิ์');
  E(`applyUser({role:'owner'})`);
  console.log('[เพิ่มพนักงานใหม่ → ไปกรอกข้อมูลส่วนตัวต่อ]');
  E(`go('emp'); openEmpForm()`); d.getElementById('fNick').value='ใหม่';
  writes.length=0; await w.eval(`saveEmpForm()`); await tick();
  const ins=writes.find(x=>x.table==='employees'&&x.op==='insert');
  ok(ins && ins.row.nick==='ใหม่' && E(`curPage()`)==='detail' && E(`detailEmpId`)===99 && E(`detailTab`)==='info' && E(`dtEditSec`)==='all' && d.getElementById('pi_birth'),'บันทึกพนักงานใหม่ → หน้ารายคน แท็บข้อมูลส่วนตัว เปิดแก้ทุกหัวข้อ');
  E(`piCancel()`);
  console.log('[ปุ่มในรายชื่อพนักงาน]');
  E(`employees.find(e=>e.id===2).phone=''; employees.find(e=>e.id===2).position='เสิร์ฟ'; go('emp')`);
  const er=nick=>[...d.querySelectorAll('#empTable tbody tr')].find(tr=>tr.cells[0].textContent.trim()===nick);
  const eye=er('บอส').querySelector('button');
  ok(eye.textContent==='👁' && eye.classList.contains('btn-alert') && /เบอร์โทร/.test(eye.title) && /openDetailInfo/.test(eye.getAttribute('onclick')),'ข้อมูลส่วนตัวขาด = ปุ่ม 👁 แดง พาไปแท็บข้อมูลส่วนตัว');
  ok(![...er('บอส').querySelectorAll('button')].find(b=>b.textContent==='✎').classList.contains('btn-alert'),'ปุ่ม ✎ ไม่แดงเพราะข้อมูลส่วนตัวแล้ว');
  console.log('[ลากหน้าลง/รีเฟรชระหว่างกรอก]');
  const orig=E(`JSON.stringify(Object.fromEntries(Object.keys(PI_F).map(k=>[k,piVal(employees.find(e=>e.id===4),k)])))`);
  const ROWS=E(`JSON.stringify([window.__row])`);
  const dom2=new JSDOM(html,{url:'https://thananant.github.io/JJ-PnL/jjmk-payroll.html#detail',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,
    beforeParse(w2){ w2.supabase={createClient:()=>({from:t=>chain(t),channel:()=>chain('ch'),rpc:()=>chain('rpc'),removeChannel(){},storage:{from:()=>({})}})}; w2.TextEncoder=require('util').TextEncoder; w2.alert=()=>{}; w2.confirm=()=>true; w2.indexedDB=undefined; w2.scrollTo=()=>{};
      w2.sessionStorage.setItem('jjpay_detail',JSON.stringify({id:1,tab:'info'}));
      w2.sessionStorage.setItem('jjpay_pidraft',JSON.stringify({emp:1,sec:'detail',orig:JSON.parse(orig),draft:{address:'ร่างที่ค้างไว้'}})); }});
  await new Promise(r=>setTimeout(r,400));
  const w2=dom2.window, E2=s=>w2.eval(s);
  E2(`applyUser({role:'owner'}); hrReady=true; empInfoReady=true; ssoReady=true; kbizReady=true; employees=${ROWS}.map(fromDbEmp); recomputeAll(); go('detail')`);
  const a2=w2.document.getElementById('pi_address');
  ok(E2(`detailTab`)==='info' && a2 && a2.value==='ร่างที่ค้างไว้','เปิดใหม่ = กลับมาที่ฟอร์มเดิม พร้อมค่าที่กรอกค้างไว้');
  writes.length=0; await w2.eval(`saveInfo()`); await tick();
  const u2=writes.find(x=>x.table==='employees'&&x.op==='update');
  ok(u2 && u2.row.address==='ร่างที่ค้างไว้','บันทึกร่างที่กู้คืนได้');
  console.log('[SQL ที่ฝังในแอป]');
  // เทียบกับไฟล์บน branch sql (ไฟล์ sql/ ในเครื่องอยู่ใน .gitignore — เครื่องอื่นอาจไม่มี)
  const emb=d.getElementById('sqlEmpHr').textContent.trim();
  let file=null; try{ file=require('child_process').execSync('git show origin/sql:jjmk-payroll/jj_employee_hr.sql',{cwd:__dirname,stdio:['ignore','pipe','ignore']}).toString().trim(); }catch(_){}
  if(file===null){ try{ file=require('fs').readFileSync(__dirname+'/../../sql/jj_employee_hr.sql','utf8').trim(); }catch(_){} }
  if(file===null) console.log('  – ข้ามการเทียบ SQL (ไม่มี origin/sql ในเครื่องนี้ — git fetch origin sql ก่อน)');
  else ok(emb===file,'SQL ในแอปตรงกับ jj_employee_hr.sql บน branch sql ทุกตัวอักษร');
}catch(e){ console.log('CRASH',e.stack); fail++; }
 if(errs.length) console.log('jsdom:',errs.filter(x=>!/scrollTo/.test(x)).slice(0,3).join(' | '));
 console.log(fail?fail+' FAILED':'ALL PASSED'); process.exit(fail?1:0);
},400);
