-- ============================================================
-- jj_loans.sql — พนักงานยืมเงิน (เงินยืมทั่วไป แยกจาก MOU)
-- เลือกได้ว่าผ่อนงวดละเท่าไร และหักตอนไหน:
--   deduct_on = 'mid'     -> หักจากยอดโอนตอนเบิกกลางเดือน (เหลือเท่าไรไปหักท้ายเดือนให้เอง)
--   deduct_on = 'payroll' -> หักตอนจ่ายเงินเดือนปกติ (ขึ้นในสลิป)
-- รันทั้งไฟล์ใน Supabase SQL Editor (Ctrl+A ก่อน Run) · รันซ้ำได้ ไม่พัง
-- ============================================================

-- 1) รายการยืมเงิน (คนละ 1 รายการที่ยังผ่อนอยู่)
CREATE TABLE IF NOT EXISTS loans (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  bigint NOT NULL UNIQUE REFERENCES employees (id) ON DELETE CASCADE,
  amount       numeric NOT NULL DEFAULT 0,
  monthly      numeric NOT NULL DEFAULT 1000,
  deduct_on    text NOT NULL DEFAULT 'payroll',
  start_period text NOT NULL DEFAULT '',
  opening      numeric NOT NULL DEFAULT 0,
  loan_date    date,
  note         text NOT NULL DEFAULT '',
  created_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN loans.amount       IS 'ยอดเงินที่ยืม';
COMMENT ON COLUMN loans.monthly      IS 'ผ่อนคืนต่องวด';
COMMENT ON COLUMN loans.deduct_on    IS 'หักตอนไหน: mid = เบิกกลางเดือน · payroll = รอบจ่ายเงินเดือน';
COMMENT ON COLUMN loans.start_period IS 'เริ่มหักตั้งแต่งวด YYYY-MM';
COMMENT ON COLUMN loans.opening      IS 'ยอดที่ผ่อนไปก่อนเริ่มใช้ระบบ';

-- 2) แก้จำนวนหักเฉพาะงวด (override)
CREATE TABLE IF NOT EXISTS loan_entries (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  period      text NOT NULL,
  amount      numeric NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, period)
);

-- 3) RLS แบบเดียวกับตารางอื่นของระบบ
ALTER TABLE loans        ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan_entries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'loans' AND policyname = 'loans_all') THEN
    CREATE POLICY loans_all ON loans FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'loan_entries' AND policyname = 'loan_entries_all') THEN
    CREATE POLICY loan_entries_all ON loan_entries FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;

-- 4) เปิด realtime ให้หน้าเว็บ sync สด
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE loans;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE loan_entries;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END
$$;
