-- ============================================================
-- jj_mou.sql — ระบบเงินยืม MOU + ทะเบียนเก็บ/ยืม/คืนเอกสาร (JJ-Payroll)
-- รันทั้งไฟล์ใน Supabase SQL Editor (โปรเจกต์ jjmk-stock) ครั้งเดียว
-- รันซ้ำได้ ไม่พัง
-- ============================================================

-- 1) รายการยืมเงิน MOU (คนละ 1 รายการ)
CREATE TABLE IF NOT EXISTS mou_loans (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id  bigint NOT NULL UNIQUE REFERENCES employees (id) ON DELETE CASCADE,
  amount       numeric NOT NULL DEFAULT 15000,
  monthly      numeric NOT NULL DEFAULT 2000,
  final_max    numeric NOT NULL DEFAULT 3000,
  start_period text NOT NULL DEFAULT '',
  opening      numeric NOT NULL DEFAULT 0,
  doc_passport boolean NOT NULL DEFAULT true,
  doc_pink     boolean NOT NULL DEFAULT true,
  doc_complete boolean NOT NULL DEFAULT false,
  note         text NOT NULL DEFAULT '',
  returned_at  date,
  created_at   timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN mou_loans.amount       IS 'ยอดเงินที่ยืมไปทำ MOU (ปกติ 15000)';
COMMENT ON COLUMN mou_loans.monthly      IS 'หักคืนต่อเดือน (ปกติ 2000)';
COMMENT ON COLUMN mou_loans.final_max    IS 'คงเหลือไม่เกินเท่านี้ หักหมดในงวดสุดท้าย (ปกติ 3000)';
COMMENT ON COLUMN mou_loans.start_period IS 'เริ่มหักตั้งแต่งวด YYYY-MM';
COMMENT ON COLUMN mou_loans.opening      IS 'ยอดที่หักไปก่อนเริ่มใช้ระบบ';
COMMENT ON COLUMN mou_loans.doc_passport IS 'บริษัทเก็บ Passport ไว้';
COMMENT ON COLUMN mou_loans.doc_pink     IS 'บริษัทเก็บบัตรชมพูไว้';
COMMENT ON COLUMN mou_loans.doc_complete IS 'เอกสาร MOU ครบถ้วนแล้ว';
COMMENT ON COLUMN mou_loans.returned_at  IS 'วันที่คืนเอกสารให้พนักงาน (คืนเมื่อหักครบ)';

-- 2) แก้จำนวนหักเฉพาะงวด (override)
CREATE TABLE IF NOT EXISTS mou_entries (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  period      text NOT NULL,
  amount      numeric NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, period)
);

-- 3) สมุดยืม-คืนเอกสาร
CREATE TABLE IF NOT EXISTS doc_borrows (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  doc         text NOT NULL,
  borrow_date date NOT NULL DEFAULT CURRENT_DATE,
  return_date date,
  note        text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN doc_borrows.doc         IS 'เอกสารที่ยืม เช่น Passport / บัตรชมพู';
COMMENT ON COLUMN doc_borrows.borrow_date IS 'วันที่ยืมออกไป';
COMMENT ON COLUMN doc_borrows.return_date IS 'วันที่นำมาคืน (ว่าง = ยังไม่คืน)';

-- 4) RLS แบบเดียวกับตารางอื่นของระบบ
ALTER TABLE mou_loans   ENABLE ROW LEVEL SECURITY;
ALTER TABLE mou_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE doc_borrows ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mou_loans' AND policyname = 'mou_loans_all') THEN
    CREATE POLICY mou_loans_all ON mou_loans FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'mou_entries' AND policyname = 'mou_entries_all') THEN
    CREATE POLICY mou_entries_all ON mou_entries FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'doc_borrows' AND policyname = 'doc_borrows_all') THEN
    CREATE POLICY doc_borrows_all ON doc_borrows FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;

-- 5) เปิด realtime ให้หน้าเว็บ sync สด
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE mou_loans;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE mou_entries;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE doc_borrows;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END
$$;
