-- ============================================================
-- jj_sso.sql — ระบบประกันสังคม (สปส.)
-- · เลือกได้รายคนว่าเข้า/ไม่เข้าประกันสังคม (employees.sso_on) + เลขบัตร ปชช. (sso_id)
-- · หักเงินสมทบอัตโนมัติ: ฐานค่าจ้าง 1,650–15,000 × 5% (ปัดเศษ ≥50 สต. ขึ้น)
--   นายจ้างสมทบเท่ากัน · แก้/งดหักรายงวดได้ (sso_entries)
-- · อัตราและฐาน แก้ได้ในหน้าตั้งค่า (sso_rate / sso_min / sso_max)
-- รันทั้งไฟล์ใน Supabase SQL Editor (Ctrl+A ก่อน Run) · รันซ้ำได้ ไม่พัง
-- ============================================================

-- 1) คอลัมน์รายพนักงาน
ALTER TABLE employees ADD COLUMN IF NOT EXISTS sso_on boolean NOT NULL DEFAULT false;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS sso_id text NOT NULL DEFAULT '';

COMMENT ON COLUMN employees.sso_on IS 'เข้าประกันสังคม (หักเงินสมทบอัตโนมัติ)';
COMMENT ON COLUMN employees.sso_id IS 'เลขประจำตัวประชาชน / เลขผู้ประกันตน 13 หลัก';

-- 2) การตั้งค่ากลาง
ALTER TABLE payroll_settings ADD COLUMN IF NOT EXISTS sso_rate numeric NOT NULL DEFAULT 5;
ALTER TABLE payroll_settings ADD COLUMN IF NOT EXISTS sso_min numeric NOT NULL DEFAULT 1650;
ALTER TABLE payroll_settings ADD COLUMN IF NOT EXISTS sso_max numeric NOT NULL DEFAULT 15000;
ALTER TABLE payroll_settings ADD COLUMN IF NOT EXISTS sso_account text NOT NULL DEFAULT '';

COMMENT ON COLUMN payroll_settings.sso_rate    IS 'อัตราเงินสมทบ % (ปกติ 5)';
COMMENT ON COLUMN payroll_settings.sso_min     IS 'ฐานค่าจ้างต่ำสุด (ปกติ 1,650)';
COMMENT ON COLUMN payroll_settings.sso_max     IS 'ฐานค่าจ้างสูงสุด (ปกติ 15,000)';
COMMENT ON COLUMN payroll_settings.sso_account IS 'เลขที่บัญชีนายจ้าง 10 หลัก (ใช้หัวเอกสาร สปส. 1-10)';

-- 3) แก้/งดหักเฉพาะงวด (override)
CREATE TABLE IF NOT EXISTS sso_entries (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  period      text NOT NULL,
  amount      numeric NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, period)
);

-- 4) RLS แบบเดียวกับตารางอื่นของระบบ
ALTER TABLE sso_entries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sso_entries' AND policyname = 'sso_entries_all') THEN
    CREATE POLICY sso_entries_all ON sso_entries FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;

-- 5) เปิด realtime ให้หน้าเว็บ sync สด
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE sso_entries;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END
$$;
