-- ============================================================
-- jj_tips.sql — ทิปประจำงวด หารเท่ากันทุกคนในสาขา
-- ใส่ยอดทิปรวมของแต่ละสาขาต่องวด ระบบหารให้คนที่มีวันทำงานในงวดนั้น
-- เท่ากันทุกคน (เศษปัดลง) แล้วบวกเข้าเงินเดือนอัตโนมัติ
-- รันทั้งไฟล์ใน Supabase SQL Editor (Ctrl+A ก่อน Run) · รันซ้ำได้ ไม่พัง
-- ============================================================

CREATE TABLE IF NOT EXISTS tips (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period     text NOT NULL,
  branch     text NOT NULL,
  amount     numeric NOT NULL DEFAULT 0,
  member_ids text NOT NULL DEFAULT '',
  note       text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (period, branch)
);

-- เผื่อคนที่รันเวอร์ชันก่อนหน้า (ยังไม่มีคอลัมน์เลือกคน) — รันซ้ำได้
ALTER TABLE tips ADD COLUMN IF NOT EXISTS member_ids text NOT NULL DEFAULT '';

COMMENT ON TABLE tips IS 'ยอดทิปรวมต่อสาขาต่องวด — แอปหารเท่ากันให้คนที่มีวันทำงานในงวด (ปัดเศษลง)';
COMMENT ON COLUMN tips.member_ids IS 'เลือกคนเอง: employee_id คั่นจุลภาค · ว่าง = อัตโนมัติ (ทุกคนที่มีวันทำงานและยังทำงานอยู่)';

ALTER TABLE tips ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'tips' AND policyname = 'tips_all') THEN
    CREATE POLICY tips_all ON tips FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE tips;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END
$$;
