-- ============================================================
-- jj_work_dates.sql — วันเริ่มงาน/วันสิ้นสุดการทำงาน + แก้ไขรายการหักอัตโนมัติ
-- · รายเดือนที่เข้าหลังเปิดงวด หรือออกก่อนตัดรอบ -> คิดค่าแรงเป็นรายวัน
-- · หักผิด (สาย/ลืมตอก/วันห้ามหยุด) แก้ยอดรายงวดได้ในตาราง fine_entries
-- รันทั้งไฟล์ใน Supabase SQL Editor (Ctrl+A ก่อน Run) ครั้งเดียว · รันซ้ำได้ ไม่พัง
-- ============================================================

-- 1) วันเริ่มงาน / วันสิ้นสุดการทำงาน ในตาราง employees
ALTER TABLE employees ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS end_date date;

COMMENT ON COLUMN employees.start_date IS 'วันเริ่มงาน — รายเดือนที่เริ่มงานกลางงวด งวดนั้นคิดเป็นรายวัน (เงินเดือน ÷ 30 × วันทำงาน)';
COMMENT ON COLUMN employees.end_date   IS 'วันสิ้นสุดการทำงาน — รายเดือนที่ออกก่อนตัดรอบ งวดนั้นคิดเป็นรายวัน';

-- 2) ตารางแก้ไขรายการหักอัตโนมัติรายงวด (หักผิดแก้ยอดได้)
--    kind: miss = หักสาย/ออกก่อน(ตามนาที) · late = ปรับมาสาย(ต่อครั้ง)
--          single = ปรับลืมตอกบัตร · must = หักหยุดวันห้ามหยุด
CREATE TABLE IF NOT EXISTS fine_entries (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id bigint NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  period      text NOT NULL,
  kind        text NOT NULL,
  amount      numeric NOT NULL DEFAULT 0,
  note        text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (employee_id, period, kind)
);

COMMENT ON TABLE fine_entries IS 'แก้ยอดรายการหักอัตโนมัติเฉพาะงวด — ไม่มีแถว = ใช้ยอดที่ระบบคิดให้';

-- 3) RLS แบบเดียวกับตารางอื่นของระบบ
ALTER TABLE fine_entries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'fine_entries' AND policyname = 'fine_entries_all'
  ) THEN
    CREATE POLICY fine_entries_all ON fine_entries
      FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;

-- 4) เปิด realtime ให้หน้าเว็บ sync สด
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE fine_entries;
  EXCEPTION WHEN duplicate_object THEN
    NULL;
  END;
END
$$;
